spring:
  datasource:
    url: jdbc:mysql:
    username: 
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
      use-new-id-generator-mapping: false
  jwt:
    header: 
    secret: 
    token-validity-in-seconds:

