spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: dongyang
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
      use-new-id-generator-mapping: false
  jwt:
    header: Authorization
    secret: efnsoifh32y9t8y4rghefjdgivfoehfwe9t4hrefjvr9gt4guaerivjqir39tguerifvgwrdfjeowjoeoASFeo9283GRERgjhfv3i9138NDVSIREg
    token-validity-in-seconds:

